#!/bin/bash

set -e

echo "grading: custom
grader_flags: ignore" > sample/testdata.yaml

echo "grading: custom
grader_flags: groups" > secret/testdata.yaml

CURGROUP=-1

rm groups cases

# Arguments testgroupname score
testgroup () {
    CURGROUP=$(( CURGROUP+1 ))
    echo "Group $CURGROUP ($1)"
    echo $1 $2 >> groups
}

# Arguments: testcasename
testcase () {
  echo $1 $CURGROUP >> cases
}

testgroup subtask1 19
testcase link01
testcase link02

testgroup subtask2 24
testcase link01
testcase link02
testcase link03
testcase link04
testcase link05

testgroup subtask3 37
testcase link01
testcase link02
testcase link03
testcase link04
testcase link05
testcase link06
testcase link07
testcase link08
testcase link09
testcase link10

testgroup subtask4 20
testcase link01
testcase link02
testcase link03
testcase link04
testcase link05
testcase link06
testcase link07
testcase link08
testcase link09
testcase link10
testcase link11
testcase link12
testcase link13
testcase link14
testcase link15
testcase link16
testcase link17
testcase link18
testcase link19
testcase link20
testcase link21
testcase link22
testcase link23
testcase link24

mkdir -p ../graders
python3 ../../../../kattis-utils/generate_grader.py > ../graders/grader.py

echo "Don't forget to add:

type:scoring
grading:
  objective: max
  range: 0 100
  on_reject: grade

to problem.yaml"
